language: en

pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: CountVectorsFeaturizer
- name: KeywordIntentClassifier
- name: LogisticRegressionClassifier
- name: FallbackClassifier
  threshold: 0.25
  ambiguity_threshold: 0.1

policies:
- name: MemoizationPolicy
- name: RulePolicy
assistant_id: 20250918-155357-frigid-parallax
