# fly.toml app configuration file for chatbot-app

app = 'chatbot-app'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 5000          # Flask will listen on this port
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[processes]
  app = "python app.py"         # explicitly start your app

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
