language: en

pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: FallbackClassifier
  threshold: 0.3

policies:
- name: MemoizationPolicy
- name: RulePolicy
assistant_id: 20250910-193238-several-model
